spring:
  application:
    name: customerms
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # Expression Language -> Ref. other properties from this context
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}